from pymongo import MongoClient

host = '10.8.8.111:27017'
conn = MongoClient(host)

# course structure
chapters = conn['onions']['chapters']
themes = conn['onions']['themes']
topics = conn['onions']['topics']

# mdp events
events = conn['ronfedb']['mdp']

# topic difficulties generated by topic_difficulty.py
topic_diff = conn['mdp']['topicDiff']
